### ISSUE TITLE
Wrong abbreviations

### ISSUE THREAD

**Issue by tomvanswam** [tomvanswam/compass-card#10]
Hi there,

Thx for this card, I like it a lot!

Something is still not ok with the direction abbreviations. With v0.0.4 and 13°, I get abbreviation N where it should be NNE. See attachment
![compass card 1](https://user-images.githubusercontent.com/40103162/89896965-98bd8000-dbde-11ea-90a5-6b50347fdec9.png)
with further details.

_Originally posted by @andilge in https://github.com/tomvanswam/compass-card/pull/8#issuecomment-671914342_

**Comment by andilge** [comment]
just fyi, home assistant Integration "Blitzortung" for lightning detection reports negative degrees (no idea up until which value). compass card can handle the pin
![2020-08-11_16-47](https://user-images.githubusercontent.com/40103162/89912775-3b7ff980-dbf3-11ea-9bb8-4d70d7ccad64.png)
 on the compass, but fails with the abbreviations and then falls back to default N. See another screenshot attached.

**Comment by andilge** [comment]
set a comment in blitzortung integration on
https://github.com/mrk-its/homeassistant-blitzortung/issues/9

**Comment by tomvanswam** [comment]
I will fix the negative degrees issue as well
