### ISSUE TITLE
Compass Keeps pointing north

### ISSUE THREAD

**Issue by tuxick** [tomvanswam/compass-card#111]
HA Version 2021.1.5

**Browser and Operating System:**
All browsers on my debian/ubuntu installs

**Description of problem:**

Points north in any browser. Entering the same sensor for "secondary entity" shows the correct azimuth. 
Sorry i can't seem to be able to attach screenshot.

**Comment by tomvanswam** [comment]
Hi, thanks for using the card and letting me know something is out of order.

A temporary workaround is to go to yaml mode editor and remove the attribute: azimuth line under the indicator-sensor. 
For the preview it shows sun.sun with attribute azimuth, but when selecting your entity, the attribute azimuth does not get removed. And your entity does not have an azimuth attribute and thats why it's showing the default north.

I fixed this for the next upcoming version (i think).

**Comment by tuxick** [comment]
Great, that works. Thanks!
