### ISSUE TITLE
Compass card shows wrong text direction

### ISSUE THREAD

**Issue by dhover** [tomvanswam/compass-card#13]
The degrees shown are ok but the wind direction (text) isn't. There is an offset needed of about 11!

The following table should be used if whole degrees are being used.

- N                value <=11
- NNE 11  < value <=33
- NE    33  < value <=56
- ENE  56  < value <=78
- E        78  < value <=101
- ESE   101 < value <=123
- SE      123 < value <=146
- SSE    146 < value <=168
- S        168 < value <=191
- SSW   191 < value <=213
- SW     213 < value <=236
- WSW  236 < value <=258
- W       258 < value <=281
- WNW 281 < value <=303
- NW    303 < value <=326
- NNW  326 < value <=348
- N         348 < value

**Comment by tomvanswam** [comment]
What version are you using? Should be fixed in v0.0.5 (see #10)

**Comment by dhover** [comment]
Hi Tom,

Im using version  0.0.5.

**Comment by tomvanswam** [comment]
Ok, strange, have to ask (stupid question, I know) have you force reloaded the page with the card on it, after updating the card? (<kbd>Ctrl</kbd>+<kbd>F5</kbd>). 
Your values are identical to the ones mentioned in #10 and I implemented those (or atleast tried to) and tested it which seemed ok to me.

At the moment my development environment is failing me so might take me a bit to get a look.

**Comment by dhover** [comment]
Now it is working. I don't know why. Maybe there was a cache in between.
I checked all the boundary values and it is perfect now!

**Comment by dhover** [comment]
One  suggestion to make it even beter: The entities are not sorted. So it it difficult to find the right one!

**Comment by tomvanswam** [comment]
Good idea, honestly i thought the list would be auto sorted. I'll check if i can sort it myself.
Thanks for letting me know it works now. I'll close the issue then.
