### ISSUE TITLE
Loading all entities when editing in graphical editor

### ISSUE THREAD

**Issue by Haringstad** [tomvanswam/compass-card#20]
**Checklist:**

- [x ] I updated to the latest version available
- [ x] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**
0.2.0
**Browser and Operating System:**
Google Chrome - Linux 
Ephipany - Linux 

**Description of problem:**
When editing the card within the graphical interface, it loads *all* entities, while sensors should be enough. This brings browsers to an almost halt. 

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by tomvanswam** [comment]
You're right, I use the input_number and input_text myself for debugging as I can easily manipulate those in my test env, so I'll keep those in as well.
