### ISSUE TITLE
localizations new languages, how to proceed?

### ISSUE THREAD

**Issue by andilge** [tomvanswam/compass-card#27]
**What is the best way to send the language json files?**

Hi Tom,

Nice to see you're making steps forward into multi language support. I can contribute Portuguese, please find it here
[pt.json.txt](https://github.com/tomvanswam/compass-card/files/5086800/pt.json.txt)

I can help out with French and Spanish as well. Ok if I follow up on this message attaching the files?

All the best, Andi

**Comment by andilge** [comment]
Find French and Spanish attached
[es.json.txt](https://github.com/tomvanswam/compass-card/files/5086891/es.json.txt)
[fr.json.txt](https://github.com/tomvanswam/compass-card/files/5086892/fr.json.txt)

**Comment by tomvanswam** [comment]
Wow, thanks a lot! With everyones help its easy to progress in multi lingual support!
Adding the files (like you did) is easiest, and works for me.

I'll add these and release a new version tonight.

**Comment by dhover** [comment]
A beginners question: where must those language files be stored and how to setup a custom language for the compass card?

**Comment by dhover** [comment]
I solved it myself. I added the language tag under the main settings and not under the compass setting!
Where are those language json files stored during the installation of the card?

**Comment by tomvanswam** [comment]
The language file are compiled into the compass-card.js.

So to add additional languages, a language.json is needed + some additional changes to a couple of source files, so the card knows about the existence of the additional languages.

**Comment by tomvanswam** [comment]
@andilge Thanks very much! 

Sure it's ok to attach the files here, I'll include them in the next update

**Comment by dhover** [comment]
@tomvanswam Ok now I understand how it works. Thanks for your answer.

**Comment by dhover** [comment]
One small addition to make it better: In the info of the card is says:
`Show the abbreviation in the language configured in Home Assistant (default/empty), or configured language`
The first time it was not clear you have to insert the 2-letters for the country code and not the whole country name.
In Home Assistant you choose your personal language from a dropdown list. That's different.
