### ISSUE TITLE
Double Tap Action & actions for each sensor

### ISSUE THREAD

**Issue by bah-sa** [tomvanswam/compass-card#374]
Hi. I use compass-card and I like it. Great thnx for it development.

I use `tap_action` to show `more-info` of my wind speed sensor. It is very convenient.
I would also like to see `more-info` of my wind direction sensor. It require once more action,
and can be implemented through `double_tap_action` or, alternatively, through separate `tap_action` for indicator sensor value.

Also, it would be nice for computer browsers, change mouse cursor style to `hand` if  `tap_action` defined.
This will indicate that the card is tapable.

Thnx in advance )

**Comment by tomvanswam** [comment]
Sounds like all great improvements. I'll put them on my todo list.

However due to my personal situation time is currently limited to implement these.

**Comment by tomvanswam** [comment]
Added doubleclick behaviour for next release.
As the per sensor click detection is not that straight forward I'm leaving that out.
