### ISSUE TITLE
Sensor attribute values

### ISSUE THREAD

**Issue by Tom-ahawk** [tomvanswam/compass-card#42]
Nice card!

Please make the card take attributes as values. 
This way the user don’t need to create additional template sensors for using the card.

![image](https://user-images.githubusercontent.com/35527507/93712545-dfe04e80-fb56-11ea-905b-0fe80ec6e7b5.png)

**Comment by tomvanswam** [comment]
This is actually something I started working on yesterday,
Consider this a feature that will be implemented in the next release.

**Comment by tomvanswam** [comment]
I should have opened a WTH topic for this, as I don't quite understand this isn't a default feature for all cards (or I'm missing something).

**Comment by Tom-ahawk** [comment]
Good to read : )

At least they started using attributes as automation triggers in the last HA release.
