### ISSUE TITLE
Wind direction history

### ISSUE THREAD

**Issue by hquick81** [tomvanswam/compass-card#43]
Hi i really like this compass. However i would love to see some history to get a better understanding of whats going on. 
My idea here would be that the wind direction will be chopped into e.g. 10° parts and for each measurement that falls into that 10° part that area at the circle will get darker for example. Or i could imagine some kind of bar getting bigger at that position as well. Like drawing a line from the center to the outer circle that represents the distribution of that segment in the monitored timeframe.

**Comment by tomvanswam** [comment]
Glad to hear you like it!

You're proposing something like this?
![wind-direction.jpg](https://user-images.githubusercontent.com/2330034/95024283-56ff0200-0682-11eb-9f2a-4595ab73ccf1.jpg)
(this is from a domoticz wind sensor)

I've thinking about this myself, having used domoticz before home-assistant.
Currently work is beeing done on a rather large part of the compass. When that is done I'll see if i can get something like that into this card.

**Comment by hquick81** [comment]
Yes ! Something like that ! I did not account for windspeeds in that history for now. I think for a start just the pure distribution of the wind direction would be enough. Thx for considering it !

**Comment by lloyda** [comment]
I'd also really appreciate something to show some form of history.  Here is another example which does not complicate things by bringing speed into it.

![image](https://user-images.githubusercontent.com/1671197/116123542-06e99a80-a6bb-11eb-8637-34ec2ebad861.png)


Great card by the way - thanks for your work on this.

**Comment by tomvanswam** [comment]
@aukedejong made a card which has all the requested features, find his card [here](https://github.com/aukedejong/lovelace-windrose-card). As my time is limited and another card already has this feature, I'm closing this feature request.
