### ISSUE TITLE
Change sun aspect after sunset

### ISSUE THREAD

**Issue by amagr0** [tomvanswam/compass-card#629]
**Is your feature request related to a problem? Please describe.**
No exactly a problem, but an enhancement.

**Describe the solution you'd like**
Change the aspect (grey, wireframe, hide, ...) of the sun after the sunset.

**Additional context**
Like the below integration, after the sunset, the sun is hidden.

![image](https://user-images.githubusercontent.com/12901952/187295616-eee6fb03-02f7-496d-ac49-144b55efeb79.png)

**Comment by tomvanswam** [comment]
Hi, this should be possible to configure already.  I currently am very limited in my time to help out, you could look into the dynamic_style settings or ask on the Home Assistant Forums thread.

**Comment by tomvanswam** [comment]
Please see https://github.com/tomvanswam/compass-card#dynamic-style--style-band-example for an example that hides sun indicator when elevation is below horizon.
