### ISSUE TITLE
The displayed wind direction does not match the sensor.

### ISSUE THREAD

**Issue by sblogoshs** [tomvanswam/compass-card#864]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

v2.0.0
HomeAssistant 2023.10.3
OS 11.0
Frontend 20231005.0 lastest

**Last working release (if known):**

**Browser and Operating System:**

Safari and App iOS 17 actual

Android 10 Chrome and App the same 

**Description of problem:**

The displayed wind direction does not match the sensor.
No setting could solve the problem so far.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**YAML config or the card with the bug:**

```

```

**Screenshots of the Developer Tools page, State tab:**
Get it here: [![Open your Home Assistant instance and show your state developer tools.](https://my.home-assistant.io/badges/developer_states.svg)](https://my.home-assistant.io/redirect/developer_states/)

**Additional information:**

![image](https://github.com/tomvanswam/compass-card/assets/26520301/38d72adc-bdd5-4fa4-a64d-e61e4dcd5246)

![image](https://github.com/tomvanswam/compass-card/assets/26520301/fb25d091-642e-4a31-bca9-870e8c89cce1)

**Comment by sblogoshs** [comment]
Without an update it works again since just now!

**Comment by tomvanswam** [comment]
I haven't had time to answer yet, however from your screenshots, which show state 0 I would say the card is working as intended. 
If 0 wasn't the correct state at that time there might be something wrong with the sensor.
This also explains it magically started working again, the sensor value is correct again.
