### ISSUE TITLE
Fontsize Option for a 2nd Value Sensor...

### ISSUE THREAD

**Issue by tomlahr** [tomvanswam/compass-card#880]
Hello,
concerning adding a second sensor I want to resize the Font:
![CompassCardFontsize](https://github.com/tomvanswam/compass-card/assets/99721319/4c6094aa-729b-4d17-9253-6a99ab7e32b4)

Is there a solution?
Thanks In Advance

Cheers!

**Comment by tomvanswam** [comment]
You could use [lovelace card mod](https://github.com/thomasloven/lovelace-card-mod) and [this post](https://community.home-assistant.io/t/compass-card-points-you-in-the-right-direction/217909/213?u=tomvanswam) as an example.

**Comment by tomlahr** [comment]
Many thanks for the quick reply and the link to the thread.
I have tried to adopt the example in the post nearly 1:1, but without any effect on the display.
(card-mod is installed properly) 
However, there were no error messages either - hmm, strange...

But I will keep tracking on this - keep the good work going..!
