### ISSUE TITLE
This is what I want

### ISSUE THREAD

**Issue by oywino** [tomvanswam/compass-card#890]
Hi,
I'd like a card that looks something like this:
![image](https://github.com/tomvanswam/compass-card/assets/18447119/64118486-64f8-4c20-af97-b4c28322b91b)
Is that possible with this integration?

1. North should always be straight up (never rotate the rose).
2. The arrow should move dynamically (real-time) around the rose.
3. The size of the arrow could change (also color change green-yellow-red) with the wind speed just to give a visual fancy feedback.

**Comment by tomvanswam** [comment]
1. ✅ This is default behaviour
2. ✅ This is default behaviour
3a. Size: ❌ This is not implemented
3b. Color: ✅ This can be done with dynamic styling, see example [here](https://github.com/tomvanswam/compass-card#dynamic-style--style-band-example)
