### ISSUE TITLE
Wrong direction ?

### ISSUE THREAD

**Issue by gypais** [tomvanswam/compass-card#892]
hello, I have a southerly wind (coming from the south), the sensor is at 171°, but the compass card indicates a direction N
It seems like the map tells me where the wind is going.
Thanks for your help.

type: custom:compass-card
header:
  title:
    value: Wind
indicator_sensors:
  - sensor: sensor.station_meteo_wind_speed
value_sensors:
  - sensor: sensor.station_meteo_wind_speed
language: fr
compass:
  north:
    show: true

**Comment by tomvanswam** [comment]
Could you add a screenshot please?
I'm not sure what is your question and a screenshot can help clear that up.

**Comment by gypais** [comment]
it's a mistake on my part, sorry and congratulations for the code

**Comment by tomvanswam** [comment]
Thanks for letting me know that all is fine now. Enjoy the card!
